<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Advice rule</name>
  <uuid>fa73a62f-ba9f-40e0-945e-11a8634788f4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Name is defined
then
    set decision to "Hello " + Name ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
