<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>modeloADS-ML</name>
  <uuid>3df2829f-6243-4c90-b719-16c0859b22f0</uuid>
  <locale>es_ES</locale>
  <definition><![CDATA[asignar a decisión  predict ( 'Mapeo de datos' ) ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
