<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>125fdd54-ffbc-4db4-b19e-5c5794d90151</uuid>
  <locale>es_ES</locale>
  <definition><![CDATA[asignar a decisión una nueva probabilidad en que
		los porcentajes are los probabilityes , 
		la respuesta es el predictión ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
